db2:
  image: 9801629b153b
  container_name: db2server
  restart: always
  ports:
      - 50000:50000
  volumes: 
      - /Docker/db2/database:/database 
  env_file:
      - db2.env
  privileged: true
