db2:
  image: store/ibmcorp/db2_developer_c:11.1.2.2
  container_name: db2server
  restart: always
  ports:
      - 50000:50000
  volumes: 
      - /data:/database 
  env_file:
      - db2.env
  privileged: true
