------------------------------
-- REORG AND RUNSTATS

REORG TABLE MEMBER INDEX IDX_MEMBER_ID ALLOW NO ACCESS ;
REORG TABLE DIVISION INDEX IDX_DIVISION_ID ALLOW NO ACCESS ;

CALL ADMIN_CMD('RUNSTATS ON TABLE '||RTRIM(CURRENT SCHEMA)||'.MEMBER WITH DISTRIBUTION AND DETAILED INDEXES ALL') ;
CALL ADMIN_CMD('RUNSTATS ON TABLE '||RTRIM(CURRENT SCHEMA)||'.DIVISION WITH DISTRIBUTION AND DETAILED INDEXES ALL') ;
